version: '2'
services:
    novnc:
        build: ./novnc
        volumes:
            - ./storage/registry:/opt/storage
        ports:
            - 8080:8080
        restart: always
        environment:
#            - PROXY_URL=proxy:8080
#            - PROCESS_URL=http://chrome:8080
            - PROCESS_URL=http://ss.lv
        networks:
            - public_net
    proxy:
        build: ./mitm
        volumes:
            - ./storage/registry:/opt/storage
        ports:
            - 7080:8080
        restart: always
        networks:
            - public_net
            - private_net
    chrome:
        build: ./chrome
        ports:
            - 8075:8080
        environment:
            - PROCESS_URL=http://upwork.com
            - PROXY_URL=proxy:8080
        networks:
            - private_net
networks:
    public_net:    
    private_net:
        internal: true