version: '2'
services:
    novnc:
        build: ./novnc
        volumes:
            - ./storage/registry:/opt/storage
        ports:
            - 8080:8080
        restart: always
        networks:
            - network1
    proxy:
        build: ./mitm
        volumes:
            - ./storage/registry:/opt/storage
        ports:
            - 7080:8080
        restart: always
        networks:
            - network1
networks:
    network1:
        external:
            name: traefik_webgateway # not really important here